### ISSUE TITLE
An error aroused by API change in 'imageio'

### ISSUE THREAD

**Issue by Ericgeese** [miliadis/DeepVideoCS#5]
I just want to point out a small error in line 50 of datasets/videocs.py
The error information shows that "'float' object cannot be interpreted as an integer".
According to _https://stackoverflow.com/questions/54778001/how-to-to-tackle-overflowerror-cannot-convert-float-infinity-to-integer_, it is caused by an update in 'imageio' in 2019. The solution is to replace reader._meta['nframes'] with reader.count_frames()

**Comment by balablb** [comment]
thanks a lot , I have the same problem

**Comment by balablb** [comment]
> I just want to point out a small error in line 50 of datasets/videocs.py
> The error information shows that "'float' object cannot be interpreted as an integer".
> According to _https://stackoverflow.com/questions/54778001/how-to-to-tackle-overflowerror-cannot-convert-float-infinity-to-integer_, it is caused by an update in 'imageio' in 2019. The solution is to replace reader._meta['nframes'] with reader.count_frames()


Have you ever had this problem?
Test: [1/1]     Time 97.376 (97.376)    PSNR -26.118 (-26.118)
Lossy conversion from float64 to uint8. Range [-0.04140618070960045, 255.0]. Convert image to uint8 prior to saving to suppress this warning.

**Comment by miliadis** [comment]
Thanks, I modernized all the code so it will now work seamlessly with Ubuntu 18.04, Python 3.9.1, PyTorch 1.7.1 and CUDA 11.0. I have also fixed the "Convert image to uint8 prior to saving to suppress this warning." message.
